In [1]:
import numpy as np

In [2]:
a = np.array([[1,3,5,7,9],[2,4,6,8,0]])
print(a)
print(type(a))

[[1 3 5 7 9]
 [2 4 6 8 0]]
<class 'numpy.ndarray'>


In [3]:
array_zeros = np.zeros(shape = (2,3,3))
print(array_zeros)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [4]:
array_ones = np.ones((2,3,3))
print(array_ones)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [11]:
array_vazio = np.empty((3,4))
print(array_vazio)

[[1.06914059e-311 2.47032823e-322 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 5.74084271e+169 4.71483903e-090 6.23124106e-038]
 [1.56154473e+184 1.22199448e+161 3.99910963e+252 6.76174197e+170]]


In [27]:
array_sequencial = np.arange(15)
print(array_sequencial)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [13]:
array_start = np.arange(50, 200, 30)
print(array_start)

[ 50  80 110 140 170]


In [30]:
array_linear = np.linspace(0, 100, num = 20, endpoint = True, retstep = True)
print(array_linear)

(array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ]), 5.2631578947368425)


In [33]:
print(array_ones.shape)
print(array_ones.size)
print(array_ones.ndim)

(2, 3, 3)
18
3


In [42]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array.ndim)
print(array.shape)

2
(3, 3)


In [43]:
array2 = array[np.newaxis,:]
print(array2.ndim)
print(array2.shape)
print(array2)

3
(1, 3, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [44]:
array3 = array[:,np.newaxis]
print(array3.ndim)
print(array3.shape)
print(array3)

3
(3, 1, 3)
[[[1 2 3]]

 [[4 5 6]]

 [[7 8 9]]]


In [50]:
print(array3[1][0][1])

5


In [53]:
print(array3[2][0][2])

9


In [59]:
array4 = np.array([1,2,3])
array5 = np.array([4,5,6])
array6 = np.array([7,8,9])

conc_4_5 = np.concatenate((array4, array5))
conc_5_6 = np.concatenate((array5, array6))
conc_4_5_6 = np.concatenate((array4, array5, array6))

print(conc_4_5)
print(conc_5_6)
print(conc_4_5_6)

[1 2 3 4 5 6]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [60]:
maior_2 = conc_4_5_6[conc_4_5_6>2]
print(maior_2)

[3 4 5 6 7 8 9]


In [67]:
resto_zero = conc_4_5_6[conc_4_5_6%3==0]
print(resto_zero)

[3 6 9]


In [69]:
print(conc_4_5_6.sum())
print(conc_4_5_6.max())
print(conc_4_5_6.min())
print(conc_4_5_6.mean())

45
9
1
5.0


In [70]:
from numpy.random import default_rng

In [75]:
rng = default_rng()
random = rng.integers(20, size = (2,3,5))
print(random)

[[[ 3  8 13 12 16]
  [11  5 19  3  8]
  [17  4  2  2  1]]

 [[19  7 16 14 11]
  [16  9 18  7 17]
  [15  4 18 15 19]]]


In [81]:
array7 = np.arange(0,20)
print(array7)
print(type(array7))
lista_array7 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
print(lista_array7)
print(type(lista_array7))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
<class 'list'>


In [83]:
from time import process_time

In [87]:
lista_array = list(rng.integers(10, 100, 1000000))
lista_array2 = list(rng.integers(10, 100, 1000000))
array3 = []
array3 = lista_array*lista_array2
print(lista_array)
print(array3)

TypeError: can't multiply sequence by non-int of type 'list'

In [99]:
array3 = []
t1 = process_time()
for i in range(len(lista_array)):
    array3.append(lista_array[i]*lista_array2[i])
t2 = process_time()
print(t2-t1)

0.0


In [100]:
array = rng.integers(10, 100, 1000000)
array2 = rng.integers(10, 100, 1000000)
print(type(array))

t1a = process_time()
array3 = array*array2
t2a = process_time()
print(array3)
print(t2a-t1a)

<class 'numpy.ndarray'>
[ 640  429 3822 ... 2940  572 1364]
0.015625
